#include "interpreter.hpp"

#include <iostream>
#include <stdexcept>


namespace Tost
{
    Interpreter::Interpreter(const std::string& source)
        : m_lexer(Lexer(source)), m_parser(Parser(m_lexer))
    {}


    void Interpreter::error(const std::string& message)
    {
        throw std::runtime_error(message);
    }

    void Interpreter::interpret()
    {
        try
        {
            m_parser.parse();
        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << std::endl;
        }
    }

    void Interpreter::executeStatement()
    {
        // TODO: logic for executing statements
        // This is where the interpreter will execute the statements
        // generated by the parser.

        // not so important for now... i think.
    }
}